#
# Unified Makefile for i386 and x86_64
#

# If you want to change application image name, set the KBUILD_IMAGE
# environment. Default KBUILD_IMAGE is 'app'.
#
# NOTICE! Be careful to add image file in git repository.
#KBUILD_IMAGE = xxx

libs-y +=
core-y += arch/x86/skeleton/

